# Generated by Django 5.2.11 on 2026-03-05 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_code_categories(apps, schema_editor):
    CodeCategory = apps.get_model("core", "CodeCategory")
    CodeCategory.objects.bulk_create(
        [
            CodeCategory(key="initiative_status", name="Initiative Status", sort_order=10),
            CodeCategory(key="initiative_role", name="Initiative Rolle", sort_order=20),
        ],
        ignore_conflicts=True,
    )


def remove_default_code_categories(apps, schema_editor):
    CodeCategory = apps.get_model("core", "CodeCategory")
    CodeCategory.objects.filter(
        key__in=["initiative_status", "initiative_role"],
    ).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sortierung"),
                ),
                (
                    "key",
                    models.SlugField(max_length=100, unique=True, verbose_name="Schl\u00fcssel"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aktualisiert von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code-Kategorie",
                "verbose_name_plural": "Code-Kategorien",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sortierung"),
                ),
                ("code", models.CharField(max_length=100, verbose_name="Code")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "short_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Kurzname"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="codes",
                        to="core.codecategory",
                        verbose_name="Kategorie",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aktualisiert von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code",
                "verbose_name_plural": "Codes",
                "ordering": [
                    "category__sort_order",
                    "category__name",
                    "sort_order",
                    "name",
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="code",
            constraint=models.UniqueConstraint(
                fields=("category", "code"), name="uniq_code_by_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="code",
            constraint=models.UniqueConstraint(
                fields=("category", "name"), name="uniq_code_name_by_category"
            ),
        ),
        migrations.CreateModel(
            name="InitiativeRoleCode",
            fields=[],
            options={
                "verbose_name": "Initiative-Rolle",
                "verbose_name_plural": "Initiative-Rollen",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.code",),
        ),
        migrations.CreateModel(
            name="InitiativeStatusCode",
            fields=[],
            options={
                "verbose_name": "Initiative-Status",
                "verbose_name_plural": "Initiative-Status",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.code",),
        ),
        migrations.RunPython(
            code=create_default_code_categories,
            reverse_code=remove_default_code_categories,
        ),
    ]
