# Generated by Django 5.2.11 on 2026-03-01 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_alter_person_options_alter_person_created_at_and_more"),
        ("strategies", "0002_remove_strategylevel_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measureresponsibility",
            options={
                "ordering": ["measure", "role", "person"],
                "verbose_name": "Massnahmenverantwortlichkeit",
                "verbose_name_plural": "Massnahmenverantwortlichkeiten",
            },
        ),
        migrations.AlterModelOptions(
            name="measuretype",
            options={
                "ordering": ["label"],
                "verbose_name": "Massnahmentyp",
                "verbose_name_plural": "Massnahmentypen",
            },
        ),
        migrations.AlterModelOptions(
            name="strategy",
            options={
                "ordering": ["title"],
                "verbose_name": "Strategie",
                "verbose_name_plural": "Strategien",
            },
        ),
        migrations.AlterModelOptions(
            name="strategylevel",
            options={
                "ordering": ["strategy", "sort_order", "title"],
                "verbose_name": "Strategieebene",
                "verbose_name_plural": "Strategieebenen",
            },
        ),
        migrations.AlterField(
            model_name="measureresponsibility",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
        ),
        migrations.AlterField(
            model_name="measureresponsibility",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Erstellt von",
            ),
        ),
        migrations.AlterField(
            model_name="measureresponsibility",
            name="measure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responsibilities",
                to="strategies.strategylevel",
                verbose_name="Massnahme",
            ),
        ),
        migrations.AlterField(
            model_name="measureresponsibility",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measure_responsibilities",
                to="people.person",
                verbose_name="Person",
            ),
        ),
        migrations.AlterField(
            model_name="measureresponsibility",
            name="role",
            field=models.CharField(
                choices=[
                    ("responsible", "Verantwortlich"),
                    ("co_responsible", "Mitverantwortlich"),
                    ("supporting", "Unterstuetzend"),
                    ("approver", "Freigebend"),
                ],
                max_length=30,
                verbose_name="Rolle",
            ),
        ),
        migrations.AlterField(
            model_name="measureresponsibility",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
        ),
        migrations.AlterField(
            model_name="measureresponsibility",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aktualisiert von",
            ),
        ),
        migrations.AlterField(
            model_name="measureresponsibility",
            name="valid_from",
            field=models.DateField(blank=True, null=True, verbose_name="Gueltig von"),
        ),
        migrations.AlterField(
            model_name="measureresponsibility",
            name="valid_until",
            field=models.DateField(blank=True, null=True, verbose_name="Gueltig bis"),
        ),
        migrations.AlterField(
            model_name="measuretype",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="measuretype",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
        ),
        migrations.AlterField(
            model_name="measuretype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Erstellt von",
            ),
        ),
        migrations.AlterField(
            model_name="measuretype",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktiv"),
        ),
        migrations.AlterField(
            model_name="measuretype",
            name="label",
            field=models.CharField(max_length=255, verbose_name="Bezeichnung"),
        ),
        migrations.AlterField(
            model_name="measuretype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
        ),
        migrations.AlterField(
            model_name="measuretype",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aktualisiert von",
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Erstellt von",
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="document_url",
            field=models.URLField(blank=True, verbose_name="Dokument-Link"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="strategies/", verbose_name="Bild"
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktiv"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="mission",
            field=models.TextField(verbose_name="Mission"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="short_description",
            field=models.TextField(verbose_name="Kurzbeschreibung"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Geplant"),
                    ("active", "Aktiv"),
                    ("inactive", "Inaktiv"),
                    ("completed", "Abgeschlossen"),
                ],
                default="planned",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Titel"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aktualisiert von",
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="valid_from",
            field=models.DateField(verbose_name="Gueltig von"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="valid_until",
            field=models.DateField(blank=True, null=True, verbose_name="Gueltig bis"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="vision",
            field=models.TextField(verbose_name="Vision"),
        ),
        migrations.AlterField(
            model_name="strategylevel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
        ),
        migrations.AlterField(
            model_name="strategylevel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Erstellt von",
            ),
        ),
        migrations.AlterField(
            model_name="strategylevel",
            name="description",
            field=models.TextField(blank=True, verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="strategylevel",
            name="level",
            field=models.CharField(
                choices=[
                    ("handlungsfeld", "Handlungsfeld"),
                    ("ziel", "Ziel"),
                    ("massnahme", "Massnahme"),
                ],
                max_length=20,
                verbose_name="Ebene",
            ),
        ),
        migrations.AlterField(
            model_name="strategylevel",
            name="measure_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="strategy_levels",
                to="strategies.measuretype",
                verbose_name="Massnahme-Typ",
            ),
        ),
        migrations.AlterField(
            model_name="strategylevel",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="strategies.strategylevel",
                verbose_name="Parent",
            ),
        ),
        migrations.AlterField(
            model_name="strategylevel",
            name="short_code",
            field=models.CharField(max_length=50, verbose_name="Kuerzel"),
        ),
        migrations.AlterField(
            model_name="strategylevel",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="Sortierung"),
        ),
        migrations.AlterField(
            model_name="strategylevel",
            name="strategy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="levels",
                to="strategies.strategy",
                verbose_name="Strategie",
            ),
        ),
        migrations.AlterField(
            model_name="strategylevel",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Titel"),
        ),
        migrations.AlterField(
            model_name="strategylevel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
        ),
        migrations.AlterField(
            model_name="strategylevel",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aktualisiert von",
            ),
        ),
    ]
