# Generated by Django 5.2.11 on 2026-03-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategies", "0006_normalize_strategy_image_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategylevel",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Enddatum"),
        ),
        migrations.AddField(
            model_name="strategylevel",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Startdatum"),
        ),
        migrations.AddField(
            model_name="strategylevel",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("planned", "Geplant"),
                    ("in_progress", "In Arbeit"),
                    ("completed", "Abgeschlossen"),
                    ("postponed", "Verschoben"),
                ],
                max_length=20,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
