# Generated by Django 5.2.11 on 2026-03-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategies", "0008_backfill_massnahme_dates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measureresponsibility",
            name="role",
            field=models.CharField(
                choices=[
                    ("responsible", "Verantwortlich"),
                    ("co_responsible", "Mitverantwortlich"),
                    ("supporting", "Unterstützend"),
                    ("approver", "Freigebend"),
                ],
                max_length=30,
                verbose_name="Rolle",
            ),
        ),
        migrations.AlterField(
            model_name="measureresponsibility",
            name="valid_from",
            field=models.DateField(blank=True, null=True, verbose_name="Gültig von"),
        ),
        migrations.AlterField(
            model_name="measureresponsibility",
            name="valid_until",
            field=models.DateField(blank=True, null=True, verbose_name="Gültig bis"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="valid_from",
            field=models.DateField(verbose_name="Gültig von"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="valid_until",
            field=models.DateField(blank=True, null=True, verbose_name="Gültig bis"),
        ),
        migrations.AlterField(
            model_name="strategylevel",
            name="short_code",
            field=models.CharField(max_length=50, verbose_name="Kürzel"),
        ),
    ]
