# Generated by Django 5.2.11 on 2026-03-04 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("strategies", "0012_strategy_sort_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="strategy",
            options={
                "ordering": ["sort_order", "title"],
                "verbose_name": "Strategie",
                "verbose_name_plural": "Strategien",
            },
        ),
    ]
