# Generated by Django 5.2.11 on 2026-03-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategies", "0013_alter_strategy_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategylevel",
            name="total_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Kosten total",
            ),
        ),
        migrations.AddField(
            model_name="strategylevel",
            name="total_effort",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Aufwand total",
            ),
        ),
    ]
