# Generated by Django 5.2.11 on 2026-03-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategies", "0014_strategylevel_total_cost_strategylevel_total_effort"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategylevel",
            name="implementation_description",
            field=models.TextField(blank=True, verbose_name="Beschreibung Umsetzung"),
        ),
    ]
