# Generated by Django 5.2.11 on 2026-03-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("strategies", "0015_strategylevel_implementation_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="strategy",
            name="is_active",
        ),
    ]
