# Generated by Django 5.2.11 on 2026-03-01 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["user__last_name", "user__first_name", "short_code"],
                "verbose_name": "Person",
                "verbose_name_plural": "Personen",
            },
        ),
        migrations.AlterField(
            model_name="person",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
        ),
        migrations.AlterField(
            model_name="person",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Erstellt von",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="function_title",
            field=models.CharField(max_length=255, verbose_name="Funktion"),
        ),
        migrations.AlterField(
            model_name="person",
            name="is_active_profile",
            field=models.BooleanField(default=True, verbose_name="Aktiv"),
        ),
        migrations.AlterField(
            model_name="person",
            name="organizational_unit",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Organisationseinheit"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="short_code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Kuerzel"),
        ),
        migrations.AlterField(
            model_name="person",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
        ),
        migrations.AlterField(
            model_name="person",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aktualisiert von",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Benutzer",
            ),
        ),
    ]
