# Generated by Django 5.2.11 on 2026-03-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_alter_person_options_alter_person_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="short_code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Kürzel"),
        ),
    ]
