# Generated by Django 5.2.11 on 2026-03-07 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def move_organizational_unit_to_fk(apps, schema_editor):
    Person = apps.get_model("people", "Person")
    Organization = apps.get_model("people", "Organization")

    organization_cache = {}
    for person in Person.objects.all():
        organizational_unit = (person.organizational_unit or "").strip()
        if not organizational_unit:
            continue

        organization = organization_cache.get(organizational_unit)
        if organization is None:
            organization, _ = Organization.objects.get_or_create(
                name=organizational_unit,
                defaults={"is_active": True},
            )
            organization_cache[organizational_unit] = organization

        person.organization_id = organization.pk
        person.save(update_fields=["organization"])


def move_organization_fk_back_to_text(apps, schema_editor):
    Person = apps.get_model("people", "Person")
    for person in Person.objects.select_related("organization"):
        person.organizational_unit = person.organization.name if person.organization_id else ""
        person.save(update_fields=["organizational_unit"])


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0005_alter_function_created_by_alter_function_updated_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sortierung"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aktualisiert von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisationen",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="person",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="people",
                to="people.organization",
                verbose_name="Organisation",
            ),
        ),
        migrations.RunPython(move_organizational_unit_to_fk, move_organization_fk_back_to_text),
        migrations.RemoveField(
            model_name="person",
            name="organizational_unit",
        ),
    ]
