# Generated by Django 5.2.11 on 2026-03-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0006_remove_person_organizational_unit_organization_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="name",
            new_name="bereich",
        ),
        migrations.AddField(
            model_name="organization",
            name="abteilung",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Abteilung"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organization",
            name="bereich",
            field=models.CharField(max_length=255, verbose_name="Bereich"),
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ["sort_order", "bereich", "abteilung"],
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisationen",
            },
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                fields=("bereich", "abteilung"),
                name="uniq_organization_bereich_abteilung",
            ),
        ),
    ]
