# Generated by Django 5.2.11 on 2026-03-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0007_organization_abteilung_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ["sort_order", "short_code", "bereich", "abteilung"],
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisationen",
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="short_code",
            field=models.CharField(blank=True, max_length=50, verbose_name="Kürzel"),
        ),
    ]
