# Generated by Django 5.2.11 on 2026-02-28 14:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("people", "0001_initial"),
        ("strategies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ControllingPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("planning_deadline", models.DateField(blank=True, null=True)),
                ("actuals_deadline", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("open_for_planning", "Offen fuer Planung"),
                            ("open_for_actuals", "Offen fuer Ist-Erfassung"),
                            ("closed", "Abgeschlossen"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("is_locked", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ControllingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Offen"),
                            ("planning_in_progress", "Planung laeuft"),
                            ("ready_for_actuals", "Bereit fuer Ist-Erfassung"),
                            ("completed", "Abgeschlossen"),
                        ],
                        default="open",
                        max_length=30,
                    ),
                ),
                ("plan_result_description", models.TextField(blank=True)),
                (
                    "plan_effort_person_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("plan_effort_description", models.TextField(blank=True)),
                (
                    "plan_cost_chf",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("plan_cost_description", models.TextField(blank=True)),
                (
                    "actual_fulfillment_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("actual_result_description", models.TextField(blank=True)),
                (
                    "actual_effort_person_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("actual_effort_description", models.TextField(blank=True)),
                (
                    "actual_cost_chf",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("actual_cost_description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controlling_records",
                        to="strategies.strategylevel",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="controlling.controllingperiod",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period__start_date", "measure__title"],
            },
        ),
        migrations.CreateModel(
            name="ControllingRecordResponsibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("responsible", "Verantwortlich"),
                            ("co_responsible", "Mitverantwortlich"),
                            ("supporting", "Unterstuetzend"),
                            ("approver", "Freigebend"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "controlling_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsibilities",
                        to="controlling.controllingrecord",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controlling_record_responsibilities",
                        to="people.person",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["controlling_record", "role", "person"],
            },
        ),
        migrations.AddConstraint(
            model_name="controllingperiod",
            constraint=models.UniqueConstraint(
                fields=("year", "month"), name="uniq_period_year_month"
            ),
        ),
        migrations.AddConstraint(
            model_name="controllingrecord",
            constraint=models.UniqueConstraint(
                fields=("period", "measure"), name="uniq_period_measure"
            ),
        ),
    ]
