# Generated by Django 5.2.11 on 2026-03-01 11:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controlling", "0001_initial"),
        ("people", "0002_alter_person_options_alter_person_created_at_and_more"),
        ("strategies", "0003_alter_measureresponsibility_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="controllingperiod",
            options={
                "ordering": ["-year", "-month", "-start_date"],
                "verbose_name": "Controlling-Periode",
                "verbose_name_plural": "Controlling-Perioden",
            },
        ),
        migrations.AlterModelOptions(
            name="controllingrecord",
            options={
                "ordering": ["-period__start_date", "measure__title"],
                "verbose_name": "Controlling-Record",
                "verbose_name_plural": "Controlling-Records",
            },
        ),
        migrations.AlterModelOptions(
            name="controllingrecordresponsibility",
            options={
                "ordering": ["controlling_record", "role", "person"],
                "verbose_name": "Record-Verantwortlichkeit",
                "verbose_name_plural": "Record-Verantwortlichkeiten",
            },
        ),
        migrations.AlterField(
            model_name="controllingperiod",
            name="actuals_deadline",
            field=models.DateField(blank=True, null=True, verbose_name="Ist-Deadline"),
        ),
        migrations.AlterField(
            model_name="controllingperiod",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
        ),
        migrations.AlterField(
            model_name="controllingperiod",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Erstellt von",
            ),
        ),
        migrations.AlterField(
            model_name="controllingperiod",
            name="end_date",
            field=models.DateField(verbose_name="Enddatum"),
        ),
        migrations.AlterField(
            model_name="controllingperiod",
            name="is_locked",
            field=models.BooleanField(default=False, verbose_name="Gesperrt"),
        ),
        migrations.AlterField(
            model_name="controllingperiod",
            name="month",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Monat"
            ),
        ),
        migrations.AlterField(
            model_name="controllingperiod",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="controllingperiod",
            name="planning_deadline",
            field=models.DateField(
                blank=True, null=True, verbose_name="Planungsdeadline"
            ),
        ),
        migrations.AlterField(
            model_name="controllingperiod",
            name="start_date",
            field=models.DateField(verbose_name="Startdatum"),
        ),
        migrations.AlterField(
            model_name="controllingperiod",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Entwurf"),
                    ("open_for_planning", "Offen fuer Planung"),
                    ("open_for_actuals", "Offen fuer Ist-Erfassung"),
                    ("closed", "Abgeschlossen"),
                ],
                default="draft",
                max_length=30,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="controllingperiod",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
        ),
        migrations.AlterField(
            model_name="controllingperiod",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aktualisiert von",
            ),
        ),
        migrations.AlterField(
            model_name="controllingperiod",
            name="year",
            field=models.PositiveIntegerField(verbose_name="Jahr"),
        ),
        migrations.AlterField(
            model_name="controllingrecord",
            name="actual_cost_chf",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Ist-Kosten CHF",
            ),
        ),
        migrations.AlterField(
            model_name="controllingrecord",
            name="actual_cost_description",
            field=models.TextField(blank=True, verbose_name="Ist-Kosten Beschreibung"),
        ),
        migrations.AlterField(
            model_name="controllingrecord",
            name="actual_effort_description",
            field=models.TextField(blank=True, verbose_name="Ist-Aufwand Beschreibung"),
        ),
        migrations.AlterField(
            model_name="controllingrecord",
            name="actual_effort_person_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Ist-Aufwand Personentage",
            ),
        ),
        migrations.AlterField(
            model_name="controllingrecord",
            name="actual_fulfillment_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Ist-Erfuellungsgrad Prozent",
            ),
        ),
        migrations.AlterField(
            model_name="controllingrecord",
            name="actual_result_description",
            field=models.TextField(blank=True, verbose_name="Ist-Ergebnis"),
        ),
        migrations.AlterField(
            model_name="controllingrecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
        ),
        migrations.AlterField(
            model_name="controllingrecord",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Erstellt von",
            ),
        ),
        migrations.AlterField(
            model_name="controllingrecord",
            name="measure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="controlling_records",
                to="strategies.strategylevel",
                verbose_name="Massnahme",
            ),
        ),
        migrations.AlterField(
            model_name="controllingrecord",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="controlling.controllingperiod",
                verbose_name="Controlling-Periode",
            ),
        ),
        migrations.AlterField(
            model_name="controllingrecord",
            name="plan_cost_chf",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Plan-Kosten CHF",
            ),
        ),
        migrations.AlterField(
            model_name="controllingrecord",
            name="plan_cost_description",
            field=models.TextField(blank=True, verbose_name="Plan-Kosten Beschreibung"),
        ),
        migrations.AlterField(
            model_name="controllingrecord",
            name="plan_effort_description",
            field=models.TextField(
                blank=True, verbose_name="Plan-Aufwand Beschreibung"
            ),
        ),
        migrations.AlterField(
            model_name="controllingrecord",
            name="plan_effort_person_days",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Plan-Aufwand Personentage",
            ),
        ),
        migrations.AlterField(
            model_name="controllingrecord",
            name="plan_result_description",
            field=models.TextField(blank=True, verbose_name="Plan-Ergebnis"),
        ),
        migrations.AlterField(
            model_name="controllingrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Offen"),
                    ("planning_in_progress", "Planung laeuft"),
                    ("ready_for_actuals", "Bereit fuer Ist-Erfassung"),
                    ("completed", "Abgeschlossen"),
                ],
                default="open",
                max_length=30,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="controllingrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
        ),
        migrations.AlterField(
            model_name="controllingrecord",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aktualisiert von",
            ),
        ),
        migrations.AlterField(
            model_name="controllingrecordresponsibility",
            name="controlling_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responsibilities",
                to="controlling.controllingrecord",
                verbose_name="Controlling-Record",
            ),
        ),
        migrations.AlterField(
            model_name="controllingrecordresponsibility",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
        ),
        migrations.AlterField(
            model_name="controllingrecordresponsibility",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Erstellt von",
            ),
        ),
        migrations.AlterField(
            model_name="controllingrecordresponsibility",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="controlling_record_responsibilities",
                to="people.person",
                verbose_name="Person",
            ),
        ),
        migrations.AlterField(
            model_name="controllingrecordresponsibility",
            name="role",
            field=models.CharField(
                choices=[
                    ("responsible", "Verantwortlich"),
                    ("co_responsible", "Mitverantwortlich"),
                    ("supporting", "Unterstuetzend"),
                    ("approver", "Freigebend"),
                ],
                max_length=30,
                verbose_name="Rolle",
            ),
        ),
        migrations.AlterField(
            model_name="controllingrecordresponsibility",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
        ),
        migrations.AlterField(
            model_name="controllingrecordresponsibility",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aktualisiert von",
            ),
        ),
    ]
