# Generated by Django 5.2.11 on 2026-03-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controlling", "0004_remove_controllingperiod_year_and_month"),
    ]

    operations = [
        migrations.RenameField(
            model_name="controllingperiod",
            old_name="actuals_deadline",
            new_name="controlling_deadline",
        ),
        migrations.AlterField(
            model_name="controllingperiod",
            name="controlling_deadline",
            field=models.DateField(
                blank=True, null=True, verbose_name="Controlling-Deadline"
            ),
        ),
    ]
