# Generated by Django 5.2.11 on 2026-03-03 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("controlling", "0005_remove_controllingperiod_actuals_deadline_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="controllingperiod",
            name="is_locked",
        ),
    ]
