# Generated by Django 5.2.11 on 2026-03-03 19:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controlling", "0006_remove_controllingperiod_is_locked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controllingperiod",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Entwurf"),
                    ("open_for_planning", "Offen für Planung"),
                    ("open_for_actuals", "Offen für Ist-Erfassung"),
                    ("closed", "Abgeschlossen"),
                ],
                default="draft",
                max_length=30,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="controllingrecord",
            name="actual_fulfillment_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Ist-Erfüllungsgrad Prozent",
            ),
        ),
        migrations.AlterField(
            model_name="controllingrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Offen"),
                    ("planning_in_progress", "Planung läuft"),
                    ("planning_completed", "Planung abgeschlossen"),
                    ("ready_for_actuals", "Bereit für Ist-Erfassung"),
                    ("completed", "Abgeschlossen"),
                ],
                default="open",
                max_length=30,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="controllingrecordresponsibility",
            name="role",
            field=models.CharField(
                choices=[
                    ("responsible", "Verantwortlich"),
                    ("co_responsible", "Mitverantwortlich"),
                    ("supporting", "Unterstützend"),
                    ("approver", "Freigebend"),
                ],
                max_length=30,
                verbose_name="Rolle",
            ),
        ),
    ]
