# Generated by Django 5.2.11 on 2026-03-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controlling", "0007_alter_controllingperiod_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="controllingrecord",
            name="aufwand_status_manual",
            field=models.CharField(
                blank=True,
                choices=[("green", "Grün"), ("yellow", "Gelb"), ("red", "Rot")],
                default="",
                max_length=10,
                verbose_name="Ampel Aufwand (manuell)",
            ),
        ),
        migrations.AddField(
            model_name="controllingrecord",
            name="kosten_status_manual",
            field=models.CharField(
                blank=True,
                choices=[("green", "Grün"), ("yellow", "Gelb"), ("red", "Rot")],
                default="",
                max_length=10,
                verbose_name="Ampel Ausgaben (manuell)",
            ),
        ),
        migrations.AddField(
            model_name="controllingrecord",
            name="umsetzung_status_manual",
            field=models.CharField(
                blank=True,
                choices=[("green", "Grün"), ("yellow", "Gelb"), ("red", "Rot")],
                default="",
                max_length=10,
                verbose_name="Ampel Umsetzungsstand (manuell)",
            ),
        ),
    ]
