# Generated by Django 5.2.11 on 2026-03-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controlling", "0010_controllingrecord_status_as_code_fk"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE controlling_controllingrecord "
                        "ADD COLUMN ampel_allgemein varchar(10) NOT NULL DEFAULT '';"
                    ),
                    reverse_sql=(
                        "ALTER TABLE controlling_controllingrecord "
                        "DROP COLUMN ampel_allgemein;"
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE controlling_controllingrecord "
                        "ADD COLUMN remarks_controlling text NOT NULL DEFAULT '';"
                    ),
                    reverse_sql=(
                        "ALTER TABLE controlling_controllingrecord "
                        "DROP COLUMN remarks_controlling;"
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE controlling_controllingrecord "
                        "ADD COLUMN remarks_planning text NOT NULL DEFAULT '';"
                    ),
                    reverse_sql=(
                        "ALTER TABLE controlling_controllingrecord "
                        "DROP COLUMN remarks_planning;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="controllingrecord",
                    name="ampel_allgemein",
                    field=models.CharField(
                        blank=True,
                        choices=[("green", "Grün"), ("yellow", "Gelb"), ("red", "Rot")],
                        default="",
                        max_length=10,
                        verbose_name="Ampel Allgemein",
                    ),
                ),
                migrations.AddField(
                    model_name="controllingrecord",
                    name="remarks_controlling",
                    field=models.TextField(blank=True, verbose_name="Remarks Controlling"),
                ),
                migrations.AddField(
                    model_name="controllingrecord",
                    name="remarks_planning",
                    field=models.TextField(blank=True, verbose_name="Remarks Planning"),
                ),
            ],
        ),
    ]
