# Generated by Django 5.2.11 on 2026-03-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controlling", "0011_controllingrecord_ampel_allgemein_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controllingrecord",
            name="remarks_controlling",
            field=models.TextField(
                blank=True, verbose_name="Bemerkungen zum Controlling"
            ),
        ),
        migrations.AlterField(
            model_name="controllingrecord",
            name="remarks_planning",
            field=models.TextField(blank=True, verbose_name="Bemerkungen zur Planung"),
        ),
    ]
